Extend GCP Dataflow provider to support templates & streaming jobs
GoogleCloudPlatform/PerfKitBenchmarker pull request #3699
Opened 2022-08-10 19:08 UTC by rarsan

- Add new `GcpDpbDataflowTemplate` provider (as subclass of `GcpDpbDataflow`) to run Dataflow templates jobs
- Collect Dataflow job stats using new utility methods to retrieve/aggregate time series data from Cloud Monitoring
- Add cost calculator method to `GcpDpbDataflow` provider to estimate job cost
- Update existing wordcount benchmark to collect job stats (e.g. Avg CPU util) in the case of Dataflow
- Add new benchmark to run Dataflow template Pub/Sub to BigQuery job
- Add sample config files `dataflow_wc_perf.yaml` and `dataflow_template_bq_perf.yaml`

2022-08-10 21:41 UTC, dorellang commented on perfkitbenchmarker/providers/gcp/gcp_dpb_dataflow.py
> +    # print(results)
Remove commented code

2022-08-11 00:12 UTC, dorellang requested changes
Comments covering up to a3da5cc (Add cost calculator method in Dataflow provider; append total cost to…). Make another PR for the next commits.

2022-08-11 00:23 UTC, dorellang commented on perfkitbenchmarker/providers/gcp/gcp_dpb_dataflow.py
> -      raise Exception('Invalid type provided to _CalculateCost()')
Consider raising a Value Error rather than a generic Exception.

2022-08-11 14:20 UTC, rarsan commented on perfkitbenchmarker/linux_benchmarks/dpb_wordcount_benchmark.py
> +  if dpb_service_instance.SERVICE_TYPE == dpb_service.DATAFLOW:
I agree. Perhaps each service can override `GetStats()` and `CalculateCost()` to be consistent across. Adding the TODO now.

2022-08-11 15:00 UTC, rarsan commented on perfkitbenchmarker/providers/gcp/gcp_dpb_dataflow.py
> +      raise Exception('Dataflow output in unexpected format.')
I was modeling this after dataproc service. `job_id` is also needed to later on fetch job stats, but makes sense to log a warning here and proceed. Updating this.

2022-08-11 15:07 UTC, rarsan commented on perfkitbenchmarker/providers/gcp/gcp_dpb_dataflow.py
> +  # @staticmethod
Removed this utility method as it's not needed anymore.

2022-08-11 15:07 UTC, rarsan commented on perfkitbenchmarker/providers/gcp/gcp_dpb_dataflow.py
> +    # BillableShuffleDataProcessed
Good catch. These are additional metrics to collect. Added TODO to capture this.

2022-08-11 16:01 UTC, rarsan commented on perfkitbenchmarker/providers/gcp/gcp_dpb_dataflow.py
> +  def GetAvgCpuUtilization(self, start_time, end_time):
Sounds great. Added type annotation here.

2022-08-11 16:42 UTC, rarsan commented on perfkitbenchmarker/providers/gcp/gcp_dpb_dataflow.py
> +        raise Exception('Unfamiliar metric type found: {}'.format(metric))
Makes sense. Logged warning instead.

2022-08-12 20:43 UTC, closed without merging