Worked on sample
GoogleCloudPlatform/PerfKitBenchmarker pull request #5257
Opened 2024-10-04 22:08 UTC by harneet862

Worked with creating a loop to get the data for sample object

2024-10-04 22:22 UTC, pmkc commented
Hi Harneet sorry we got cut off:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork is what I was going to suggest for pulling changes to your repo (and then pulling from your own GitHub)

2024-10-07 16:43 UTC, jellyfishcake reviewed
It would be helpful to add a unit test. To do so, I recommend:
1) factor out the parsing into a new function. i.e.
def ParseOutput(stdout):
  samples = []
  ...
  return samples

Your unit test should be a new file in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/tree/master/tests/linux_benchmarks called cryptsetup_test.py

In this file, you should include the expected output as a string, and call your parse function. 
See https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/tests/linux_benchmarks/cassandra_stress_benchmark_test.py for an example.

2024-10-07 17:46 UTC, pmkc commented on perfkitbenchmarker/linux_benchmarks/cryptsetup_benchmark.py
> +      unit = ''.join(list[2:4])
I think this needs to be `[2:5]`, because the second one is inclusive.
We also want `'  '.join` to not have "iterationspersecond" smooshed together.

2024-10-07 17:48 UTC, pmkc requested changes

2024-10-07 17:48 UTC, pmkc commented on perfkitbenchmarker/linux_benchmarks/cryptsetup_benchmark.py
> +      metadata = list[6]
Oh and this needs to be a dictionary.
Something like:
`metadata = {'key_size': list[6]}`

2024-10-07 17:48 UTC, pmkc commented on perfkitbenchmarker/linux_benchmarks/cryptsetup_benchmark.py
> +      list = line.split()
could this be renamed to `words` or something  besides list to avoid colliding with the python builtin `list`?

2024-10-16 18:23 UTC, pmkc commented
I'll tweak this and merge it.

2025-05-02 20:42 UTC, closed without merging