Added accelerated openssl installation support
GoogleCloudPlatform/PerfKitBenchmarker pull request #5272
Opened 2024-10-08 08:09 UTC by rickit2022

- Added QAT installation support for accelerated OpenSSL using features as specified in #5248

2024-10-08 16:27 UTC, jellyfishcake requested changes

2024-10-08 16:27 UTC, jellyfishcake commented on perfkitbenchmarker/linux_packages/openssl.py
> +  vm.RemoteCommand('cmake . -Bbuild -DCMAKE_INSTALL_PREFIX=/usr')
Every remote command starts a new shell session. Therefore, you are back in home directory here and cannot directly call cmake.
To fix, merge line 38 and 39 by doing 
cd ipp-crypto/sources/ippcp/crypto_mb && cmake . -Bbuild -DCMAKE_INSTALL_PREFIX=/usr

2024-10-08 16:27 UTC, jellyfishcake commented on perfkitbenchmarker/linux_packages/openssl.py
> +  vm.RemoteCommand('git checkout ippcp_2021.7.1')
Every remote command starts a new shell session. Therefore, you are back in home directory here and cannot directly call cmake.
To fix, merge line 36 and 37 by doing
cd cd ipp-crypto && git checkout ippcp_2021.7.1

2024-10-08 16:27 UTC, jellyfishcake commented on perfkitbenchmarker/linux_packages/openssl.py
> +  vm.RemoteCommand('git checkout v1.3')
same issue here and in the next two commands.

2024-10-08 16:27 UTC, jellyfishcake commented on perfkitbenchmarker/linux_packages/openssl.py
> +  vm.RemoteCommand('git checkout v1.2.0')
same issue here and in the next 4 commands

2024-10-09 15:18 UTC, rickit2022 commented
@jellyfishcake Hi thanks for the comments, I had no idea about that behavior and have now put all commands on the same call(s). Please let me know if there's anything else I need to change.

2024-10-11 17:27 UTC, jellyfishcake approved these changes

2024-10-11 17:28 UTC, jellyfishcake commented
Looks good, thank you!

2024-10-11 20:38 UTC, merged